source 'https://rubygems.org'


gem 'rails', '4.1.7'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'active_model_serializers'

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :test do
  gem 'shoulda-matchers'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
end

gem 'bcrypt'
gem 'byebug'
